### ISSUE TITLE
patch 5.9-r8

### ISSUE THREAD

**Issue by kevall474** [hamadmarri/cachy-sched#16]
Can I use the 5.9-r8 patch with any 5.9.x kernel release?

**Comment by hamadmarri** [comment]
I hope so. The patch made on v5.9.1. I think it will patch successfully newer sub-versions.

Thank you

**Comment by raykzhao** [comment]
Hi @kevall474 

The patch 5.9-r8 should work with the latest Linux 5.9 kernel (5.9.8).

**Comment by kevall474** [comment]
Yes I tested it on 5.8.9-xanmod1 with no isues. But how you disable FAIR_GROUP_SCHED

**Comment by raykzhao** [comment]
Hi @kevall474 

Cachy 5.9-r8 can support FAIR_GROUP_SCHED. I'm currently using the autogroup. There is also the xanmod 5.9-cachy branch (https://github.com/xanmod/linux/tree/5.9-cachy) with both FAIR_GROUP_SCHED and autogroup enabled.

**Comment by kevall474** [comment]
Ok thanks FAIR_GROUP_SCHED was enable in my xanmod build with no problems. I was referring to this reddit post https://www.reddit.com/r/linux/comments/i32j1q/cachysched_patch_for_linux_kernel_58/ 

Its good to know that it can support  FAIR_GROUP_SCHED

**Comment by hamadmarri** [comment]
> Ok thanks FAIR_GROUP_SCHED was enable in my xanmod build with no problems. I was referring to this reddit post https://www.reddit.com/r/linux/comments/i32j1q/cachysched_patch_for_linux_kernel_58/
> 
> Its good to know that it can support FAIR_GROUP_SCHED

Hi @kevall474 

Yes, the first version of Cachy didn't support NUMA nor FAIR_GROUP, but that was fixed later.

Anyway fair_group is added in CFS to enhance the interactivity and share the cpu among multiple users.  IMO Cachy doesn't need fair_group nor autogroup for interactivity since it uses HRRN policy which by nature
will pick the highest response ratio task. You might have some performance increase by disabling Autogroup and FAIR_GROUP since they have huge code implementation in fair.c, but it is not always the case.

Thank you
