### ISSUE TITLE
Big score drop at geekbench with cachy cpu scheduler

### ISSUE THREAD

**Issue by arabcian** [hamadmarri/cachy-sched#8]
Hi with 5.8.6 Kernel, i get around 4700~ score with PDS scheduler but only get 4200 with cachy, i think that 500 points come from numa=y option in the kernel, is there way cachy to be modified to work with numa=y ?

Update: I've patched 5.7.19 with the 5.7.10 patch from the repository and i dont see a geekbench score reduction with numa=n. I get 4700~. But im not sure if cachy is really active right now. I dont see a cachy option in the kernel configuration menu. And the patch file was too small comparing the 5.8.3 patch. Can you explain why my score dropped that much with 5.8.3?

**Comment by hamadmarri** [comment]
Hi arabcian,

You can confirm by running `dmesg | grep -i "cachy cpu" `
the output will be something like:
Cachy CPU scheduler v5.7.10 by Hamad Al Marri. Thanks to my wife Sarah for her patience.

NUMA is used when you have pluggable cpus hardware. Your machine (if having no hardware to plug new cpu/s while running) might not using NUMA even if it is enabled in the kernel, correct me if I am wrong.

The size of patch in 5.8.3 is because the changes are put into cachy.c file instead of editing the original fair.c file which commit the whole new file.

I am noticing a performance drop when using 5.8.* with/without Cachy patch on my machine.  I don't know why.  I suggest you try this  https://github.com/hamadmarri/linux/tree/fix_tasks_starving for v5.9-rc3

**Comment by arabcian** [comment]
Ok, Yes Cachy is active, about numa is only thing i know that its recommended in kernel help page, if you use 1st gen corei7 or later. Another thing i realize is performance drop is only happen with Geekbench when numa is deactivated. Using hardinfo i see no performance drop with cachy and and even there is some boost. After extensive texts i found, i dont lose performance moving to 5.8, maybe its related to your hardware configuration.

**Comment by hamadmarri** [comment]
>After extensive texts i found, i dont lose performance moving to 5.8, maybe its related to your hardware configuration
Yes, I think it is related to my config and hardware.

I will be happy to see any kind of comparison results between cachy and other schedulers even if it is not on the favor of cachy.

Thank you
